import Cards from "@/components/elements/community/Cards";
import Header from "@/components/elements/community/Header";
import MainLayout from "@/components/mainLayout";
import Title from "@/components/ui/title";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "DroidHub | Communities",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <MainLayout>
      <main>
        <Title title="Communities" />
        <Header />

        <article className="mt-8">
          <Cards />
        </article>
      </main>
    </MainLayout>
  );
};

export default Page;
