import Navbar from "@/components/elements/Navbar";
import Posts from "@/components/elements/Posts";
import LeftSidebar from "@/components/elements/LeftSidebar";
import { Metadata } from "next";
import ErrorBoundary from "../components/ErrorBoundary";
import RightSidebar from "@/components/elements/RightSidebar";

export const metadata: Metadata = {
  title: "DroidHub | Home",
  description: "Generated by create next app",
};

export default async function Home() {
  return (
    <>
      <main className="h-screen overflow-hidden">
        <article className="lg:hidden">
          <Navbar />
        </article>
        <div className="flex items-start gap-4">
          <article className="hidden lg:block w-[250px] xl:w-[300px] h-screen p-4 rounded-md shadow-md bg-secondary">
            <LeftSidebar />
          </article>
          <article
            style={{ height: "calc(100vh - 74px)" }}
            className="lg:!h-screen overflow-auto flex-1 p-4 rounded-md shadow-md bg-secondary scrollbar-hide"
          >
            <ErrorBoundary>
              <Posts />
            </ErrorBoundary>
          </article>
          <article className="hidden md:block w-[300px] p-3 bg-secondary">
            <RightSidebar />
          </article>
        </div>
      </main>
    </>
  );
}
