import Posts from "@/components/elements/Posts";
import { Metadata } from "next";
import MainLayout from "@/components/mainLayout";
import Header from "@/components/elements/Header";

export const metadata: Metadata = {
  title: "DroidHub | Home",
  description: "Generated by create next app",
};

export default async function Home() {
  return (
    <MainLayout>
      <Header title="Feed" />
      <Posts />
    </MainLayout>
  );
}
